// Generated by gencpp from file number_comm/ThreeInts.msg
// DO NOT EDIT!


#ifndef NUMBER_COMM_MESSAGE_THREEINTS_H
#define NUMBER_COMM_MESSAGE_THREEINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace number_comm
{
template <class ContainerAllocator>
struct ThreeInts_
{
  typedef ThreeInts_<ContainerAllocator> Type;

  ThreeInts_()
    : num1(0)
    , num2(0)
    , num3(0)  {
    }
  ThreeInts_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)
    , num3(0)  {
  (void)_alloc;
    }



   typedef int64_t _num1_type;
  _num1_type num1;

   typedef int64_t _num2_type;
  _num2_type num2;

   typedef int64_t _num3_type;
  _num3_type num3;





  typedef boost::shared_ptr< ::number_comm::ThreeInts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::number_comm::ThreeInts_<ContainerAllocator> const> ConstPtr;

}; // struct ThreeInts_

typedef ::number_comm::ThreeInts_<std::allocator<void> > ThreeInts;

typedef boost::shared_ptr< ::number_comm::ThreeInts > ThreeIntsPtr;
typedef boost::shared_ptr< ::number_comm::ThreeInts const> ThreeIntsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::number_comm::ThreeInts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::number_comm::ThreeInts_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::number_comm::ThreeInts_<ContainerAllocator1> & lhs, const ::number_comm::ThreeInts_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2 &&
    lhs.num3 == rhs.num3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::number_comm::ThreeInts_<ContainerAllocator1> & lhs, const ::number_comm::ThreeInts_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace number_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::number_comm::ThreeInts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::number_comm::ThreeInts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::number_comm::ThreeInts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::number_comm::ThreeInts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::number_comm::ThreeInts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::number_comm::ThreeInts_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::number_comm::ThreeInts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d670a0bdbd30e1dc45f2b18311d15c64";
  }

  static const char* value(const ::number_comm::ThreeInts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd670a0bdbd30e1dcULL;
  static const uint64_t static_value2 = 0x45f2b18311d15c64ULL;
};

template<class ContainerAllocator>
struct DataType< ::number_comm::ThreeInts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "number_comm/ThreeInts";
  }

  static const char* value(const ::number_comm::ThreeInts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::number_comm::ThreeInts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num1\n"
"int64 num2\n"
"int64 num3\n"
;
  }

  static const char* value(const ::number_comm::ThreeInts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::number_comm::ThreeInts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
      stream.next(m.num3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThreeInts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::number_comm::ThreeInts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::number_comm::ThreeInts_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num2);
    s << indent << "num3: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NUMBER_COMM_MESSAGE_THREEINTS_H
